### ISSUE TITLE
Placeholder text does not appear for search bar when expanded

### ISSUE THREAD

**Issue by bazhip** [Teradata/covalent-quickstart#25] opened 2016-12-30 12:19 UTC
This repository's issues are reserved for feature requests and bug reports.

### Do you want to request a *feature* or report a *bug*?
bug
#### Feature Request

please first make sure your request falls under the official Material Design spec guidelines https://material.google.com/

#### Bug Report

please provide steps to reproduce and if possible screenhots or animated Gifs.
you can easily create animated Gif with this free PC/OSX App: http://www.cockos.com/licecap/

##### Screenshots or link to CodePen/Plunker/JSfiddle
![searchbar](https://cloud.githubusercontent.com/assets/10350445/21564981/ca0ef1cc-ce57-11e6-8432-d905bb4bcf82.gif)

#### What is the expected behavior?
I'd think the placeholder text should appear when the search is expanded so that they know what the field is for. I ended up adding a block of text to the side for the time being until I play with it more.

#### What is the motivation / use case for changing the behavior?
^
#### Which version of Angular and Material, and which browser and OS does this issue affect?
I'm on the latest build (with 2.4.1) and using chrome

Did this work in previous versions of Angular / Material?
Please also test with the latest stable and snapshot versions.
Haven't checked the others

##### Other information
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix)

**Comment by emoralesb05** [comment] 2016-12-30 16:44
The problem is we autofocus when you click on the `icon` and we hide the placeholder when focused.. we might need to add an attribute to make that optional though.

Can you please create this issue or at least link it in https://github.com/Teradata/covalent/issues?

**Comment by bazhip** [comment] 2017-01-01 23:45
Yeah I deduced that after playing with it for a minute. I just edited it to not focus, but an option would be great to have.

**Comment by emoralesb05** [comment] 2017-01-02 00:35
Sure, we can continue our talk in the `covalent` issues
Ill close this issue in favor of https://github.com/Teradata/covalent/issues/226

**Closed by emoralesb05** 2017-01-02 00:35 UTC
