### ISSUE TITLE
Example fails on npm i

### ISSUE THREAD

**Issue by Sledge-** [Teradata/covalent-quickstart#73] opened 2017-07-13 13:38 UTC
#### What is the expected behavior?
The example will install sucessfully on Windows.

#### Which version of Angular and Material, and which browser and OS does this issue affect?
This affects the most recent version as of 7-13-2017

I am trying to install the example on my Windows laptop, but it fails on the second to last step `npm i`.

Here is the error message, log file attached below:

```
PS C:\Users\ks777e\Angular\covalent-quickstart> npm i

> covalent-quickstart@1.0.0 postinstall C:\Users\ks777e\Angular\covalent-quickstart
> webdriver-manager update && ./scripts/protractor.sh

[16:25:42] I/update - chromedriver: file exists C:\Users\ks777e\Angular\covalent-quickstart\node_modules\protractor\node
_modules\webdriver-manager\selenium\chromedriver_2.30.zip
[16:25:42] I/update - chromedriver: unzipping chromedriver_2.30.zip
[16:25:42] I/update - chromedriver: chromedriver_2.30.exe up to date
[16:25:42] I/update - selenium standalone: file exists C:\Users\ks777e\Angular\covalent-quickstart\node_modules\protract
or\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.4.0.jar
[16:25:42] I/update - selenium standalone: selenium-server-standalone-3.4.0.jar up to date
[16:25:43] I/update - geckodriver: file exists C:\Users\ks777e\Angular\covalent-quickstart\node_modules\protractor\node_
modules\webdriver-manager\selenium\geckodriver-v0.18.0.zip
[16:25:43] I/update - geckodriver: unzipping geckodriver-v0.18.0.zip
[16:25:43] I/update - geckodriver: geckodriver-v0.18.0.exe up to date
'.' is not recognized as an internal or external command,
operable program or batch file.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! covalent-quickstart@1.0.0 postinstall: `webdriver-manager update && ./scripts/protractor.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the covalent-quickstart@1.0.0 postinstall script 'webdriver-manager update && ./scripts/protractor.sh
'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with th
[npm-debug.txt](https://github.com/Teradata/covalent-quickstart/files/1145327/npm-debug.txt)
e covalent-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webdriver-manager update && ./scripts/protractor.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs covalent-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls covalent-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ks777e\Angular\covalent-quickstart\npm-debug.log
PS C:\Users\ks777e\Angular\covalent-quickstart> npm bugs covalent-quickstart
```

Node and npm versions:
```
PS C:\Users\ks777e\Angular\covalent-quickstart> node --version
v6.11.1
PS C:\Users\ks777e\Angular\covalent-quickstart> npm --version
3.10.10
```

I also tried converting my postinstall attribute in package.json to `"postinstall": "webdriver-manager update && bash ./scripts/protractor.sh"`, which also did not help.

Any suggestions what to try next?

**Comment by emoralesb05** [comment] 2017-07-13 14:40
wrap ./scripts/protractor.sh in `"`.

e.g.
"postinstall": "webdriver-manager update && bash \"./scripts/protractor.sh\"" 

If that fails, just remove the `bash \"./scripts/protractor.sh\""` part which in reality doesnt do much.

**Comment by kyleledbetter** [comment] 2017-07-13 14:40
Hmm can you test with Node 6.9.5

**Comment by Sledge-** [comment] 2017-07-13 15:12
@emoralesb05 adding single quotes around ./scripts/protractor.sh didn't help but removing that part did get me through to the next step.  

Another thing I found was that the path to the covalent icon in index.html is incorrect.  I changed it to :
'<img src="**src**/assets/icons/covalent.svg" width="200">'.

So now I'm looking at a nice looking loading screen without anything else happening :).  There are no errors but I assume there is more to the example then this?  

Any suggestion what to troubleshoot?  Also, I am serving up the example in Brackets, not sure if this matters.

![covalent loading screen](https://user-images.githubusercontent.com/5295572/28173321-187442b0-67bc-11e7-89ce-c0c612b89178.PNG)

**Comment by d3viant0ne** [comment] 2017-07-13 23:23
![screen shot 2017-07-13 at 6 22 57 pm](https://user-images.githubusercontent.com/8420490/28191836-54e6709c-67f8-11e7-8fb8-a15d8c2e2e28.png)

@kyleledbetter ^^^ That isn't going to work on Windows

**Comment by mikehutter** [comment] 2017-08-24 15:23
This is a dupe of #68.  

On windows the postinstall task needs to be:

`"npm run webdriver-update && bash ./scripts/protractor.sh"`

I also ran into another issue after I changed the postinstall task as mentioned above:

```
./scripts/protractor.sh: line 2: $'\r': command not found
: No such file or directoryne 3: cd: ./node_modules/protractor/node_modules
./scripts/protractor.sh: line 4: $'\r': command not found
./scripts/protractor.sh: line 10: syntax error: unexpected end of file
```

and found the solution to that here:

https://learningintheopen.org/2013/03/07/microsoft-windows-cygwin-error-r-command-not-found/

**Comment by jeremysmartt** [comment] 2019-04-22 17:50
closing as duplicate of #68

**Closed by jeremysmartt** 2019-04-22 17:50 UTC
