### ISSUE TITLE
You have to be inside an angular-cli project in order to use the serve command.

### ISSUE THREAD

**Issue by enzonotario** [Teradata/covalent-quickstart#51] opened 2017-03-08 14:08 UTC
#### Bug Report

I just cloned this repo, run all the commands and when I try to run ng serve it has an error:
```You have to be inside an angular-cli project in order to use the serve command.```
And I'm sure that I'm in the correct folder!

I have another project that works, cloned for this quickstart (version of covalent 0.10.0), but now I want to have the latest version of covalent. I think that is better cloned the repo again and only copy my ```src``` folder...

I'm on LinuxMint 18 and have node v6.10.0 and npm v4.3.0

Thanks!

**Comment by emoralesb05** [comment] 2017-03-08 15:43
The problem is the `@angular/cli`, you need to upgrade it too.

**Comment by enzonotario** [comment] 2017-03-08 17:25
Yes, I have the latest @angular/cli...
I upgrade all dependencies

**Comment by emoralesb05** [comment] 2017-03-08 17:40
With the necessary code changes? There were breaking changes and introduced file updated that need to be done when pointing to the latest `cli`.

https://github.com/angular/angular-cli/wiki/stories-rc-update

**Comment by enzonotario** [comment] 2017-03-08 17:49
I cloned this repo again and I'm trying to run the quickstart without any modification. Then I will copy my old src, but first I'm trying to run the quickstart and have that error...

**Comment by enzonotario** [comment] 2017-03-08 18:15
Sorry sorry! I do all that the README says, but I have to do ```npm install -g @angular/cli```, instead of ```npm i -g angular-cli@latest``` (that is what the README says, why?)

Thanks!

**Comment by emoralesb05** [comment] 2017-03-08 18:45
They rebranded the CLI, since now its part of the `@angular` scope. So you need to install `@angular/cli` because `angular-cli` is deprecated.

**Comment by enzonotario** [comment] 2017-03-08 18:46
Yes, now it works fine. Thanks!

But I think that the README of this repo have to change? to indicate the new name of the angular cli dependency...

**Comment by emoralesb05** [comment] 2017-03-08 21:08
Ah yes, we forgot to update that. Thanks for the heads up.

Closing this since it was a CLI issue. 😄

**Closed by emoralesb05** 2017-03-08 21:08 UTC
